### ISSUE TITLE
[bug] oxyromon has issues with special characters

### ISSUE THREAD

**Issue by acuteaura** [alucryd/oxyromon#167] opened 2024-12-12 16:06 UTC
some rom files have some special characters that break a few commands, notably `convert-roms` invoking `7z`, but specifically `=` also broke import.

observed characters: 

* `+`
* `'`
* `=`

the commands simply get stuck forever

### Environment

* NixOX + nix-ld to run oxyromon glibc
* ZFS
* fish shell

**Comment by alucryd** [comment] 2024-12-15 22:12
Thanks for opening an issue, seems to be a duplicate of https://github.com/alucryd/oxyromon/issues/96, or at least it complements it. Afraid I don't have a solution yet, ideally I would handle archives in pure rust instead of using 7z and its flaws, but I have yet to find a suitable replacement. I may have to implement some character switcheroo to work around it, maybe renaming files before compressing them, then renaming them inside the archive (which may or may not work).

**Comment by alucryd** [comment] 2024-12-29 09:25
Apparently there was a super easy fix, which was to pass `--` before positional arguments, which signals the end of option arguments. That way 7z does not try to evaluate special characters in filenames. Added that in https://github.com/alucryd/oxyromon/commit/1d873532b874a0e4b411f4c0a16128f17d753d42

**Comment by alucryd** [comment] 2024-12-29 21:50
0.20.0 just released with the fix. Please feel free to reopen if the issue persists.

**Closed by alucryd** 2024-12-29 21:50 UTC

**Comment by acuteaura** [comment] 2024-12-30 10:00
I have moved my primary romset to use igir for now and not enough space to run a dupe right now. It'll be a week or so until I have better drives and I'll give it a go then, thanks!
